id: P005532
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19086
  title: 'དཔེ་ཆ་བཀླག་ཐབས།

    '
  author: ''
  volumes:
    d11025216cd74c58a38a554ad21111e6:
      image_group_id: I2PD20262
      title: ''
      volume_number: 1
      total_pages: 214
      base_file: v001.txt
